#!/usr/bin/env sh
# pull updates from a directory
# requires `rsync`
DEST=.
EXCLUDE=
HELP="pull updates from a directory
Usage: $0 [OPTIONS] SRC [DEST]
DEST
	destination directory
	(defaults to the CWD)
OPTIONS
	-d FILE
		list FILE of subpaths to not delete
		(defaults to \`.pull-nodelete.lst\`)
	-h
		print this text and exit
	-n FILE
		list FILE of subpaths to not pull
		(defaults to \`.pull-nopull.lst\`)
	-p FILE
		list FILE of subpaths to pull
		(defaults to \`.pull.lst\`)
SRC
	source directory"
NODELETE=.pull-nodelete.lst
NOPULL=.pull-nopull.lst
PULL=.pull.lst
RSYNC_CMD="rsync -arv --delete"
SRC=

cleanup() {
	rm -f "${EXCLUDE}"
}

# parse arguments

set -- $(getopt d:hn:p: -- "$@")

while true
do
	case "$1"
	in
	-d)
		NODELETE="$2"
		[ ! -f "${NODELETE}" ] \
			&& echo "\`${NODELETE}\` isn't a file." >&2 \
			&& exit 1
		shift
		;;
	-h)
		echo "${HELP}" >&2 \
			&& exit
		;;
	-n)
		NOPULL="$2"
		[ ! -f "${NOPULL}" ] \
			&& echo "\`${NOPULL}\` isn't a file." >&2 \
			&& exit 1
		shift
		;;
	-p)
		PULL="$2"
		shift
		;;
	--)
		shift
		break
		;;
	*)
		echo "${HELP}" >&2 \
			&& exit 1
		;;
	esac
	shift
done

[ -n "$2" ] \
	&& DEST="$2"
[ ! -d "${DEST}" ] \
	&& echo "\`${DEST}\` isn't a directory." >&2 \
	&& exit 1

[ ! -f "${PULL}" ] \
	&& echo "\`${PULL}\` isn't a file." >&2 \
	&& exit 1

SRC="$1"
[ $# -eq 0 ] \
	&& echo "${HELP}" >&2 \
	&& exit 1
[ ! -d "${SRC}" ] \
	&& echo "\`${SRC}\` isn't a directory." >&2 \
	&& exit 1

if [ -f "${NODELETE}" ] \
		|| [ -f "${NOPULL}" ]
then
	# generate an exclude file

	trap cleanup EXIT HUP INT TERM
	EXCLUDE="$(mktemp)"

	[ -f "${NODELETE}" ] \
		&& while IFS= read -r SUB
			do
				[ -n "$(echo "${SUB}" | tr -d "[:space:]")" ] \
					&& [ ! -e "${SRC}/${SUB}" ] \
					&& [ -e "${DEST}/${SUB}" ] \
					&& echo "${SUB}" >> "${EXCLUDE}"
			done < "${NODELETE}"

	[ -f "${NOPULL}" ] \
		&& while IFS= read -r SUB
			do
				[ -n "$(echo "${SUB}" | tr -d "[:space:]")" ] \
					&& [ -e "${SRC}/${SUB}" \
					&& echo "${SUB}" >> "${EXCLUDE}"
			done
	RSYNC_CMD="${RSYNC_CMD} --exclude-from=${EXCLUDE}"
fi

# pull

while IFS= read -r SUB
do
	[ -z "$(echo "${SUB}" | tr -d "[:space:]")" ] \
		&& continue
	DP="$(dirname "${DEST}/${SUB}")"
	S="${SRC}/${SUB}"
	[ ! -e "${S}" ] \
		&& continue
	! mkdir -p "${DP}" \
		&& echo "Failed to make directory \"${DP}\"." >&2 \
		&& exit 1
	! ${RSYNC_CMD} "${S}" "${DP}" \
		&& echo "\`rsync\` failed." >&2 \
		&& exit 1
done < "${PULL}"

